[package]
name = "warp-ructe"
version = "0.4.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["warp", "sass", "mime03"] }

[dependencies]
warp = "0.1.9"
mime = "0.3.0"
env_logger = "0.7.1"
