[package]
name = "gotham-ructe"
version = "0.12.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["sass", "mime03"] }

[dependencies]
gotham = "0.5.0"
gotham_derive = "0.5.0"
serde = "~1.0.66"  # Must match gotham dependency
serde_derive = "~1.0.66"  # Must match gotham dependency
mime = "~0.3.8"
